name: Test Full Stack App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install backend dependencies
      working-directory: backend
      run: npm install

    - name: Start backend server in background
      working-directory: backend
      run: |
        nohup node server.js > output.log 2>&1 &
        sleep 5

    - name: Test POST request to backend
      run: |
        curl -X POST http://localhost:3000/api/form \
        -H "Content-Type: application/json" \
        -d '{"nombre": "Juan", "email": "juan@ejemplo.com"}'

    - name: Install frontend dependencies and build
      working-directory: frontend
      run: |
        npm install
        npm run build
